<a href="https://colab.research.google.com/github/JyotiKumari-git/Python-pandas-codes-notes-practice/blob/main/Pandas_Practice_Jyoti.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#PRACTICE OF PANDAS-->

# import pandas as pd   #use alias for pandas

#1.create dataframe
# 2.basic dataframe understanding
# 3.save and load data from csv
# 4.rows and column selection
# 5.filter dataframe
# 6.rows and column operations
# 7.working with date value
# 8.handling missing values
# 9.Aggregation and groupby
# 10.concatenate and merge the dataframe

In [ ]:
#1.Dataframe Creation:
import pandas as pd
     ##Using the dataframe function for frame the data
     ##using columns func for write then colmn name
df=pd.DataFrame([10,20,30],columns=['colmn_name'])
print(df)

   colmn_name
0          10
1          20
2          30

In [ ]:
#toc heck the datatype :
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
#example of creating dataframe:
import pandas as pd


Emp_Data={
    'Name':['Madhav','Lalita','Isha','Rohan','Priya','Mina'],
    'Age':[26,25,22,27,24,23],
    'Salary':[20000,32000,28000,18000,35000,42000],
    'City':['Delhi','Kolkata','gujrat','Orrisa','Bihar','Banglore']
}
df=pd.DataFrame(Emp_Data)
print(df)

     Name  Age  Salary      City
0  Madhav   26   20000     Delhi
1  Lalita   25   32000   Kolkata
2    Isha   22   28000    gujrat
3   Rohan   27   18000    Orrisa
4   Priya   24   35000     Bihar
5    Mina   23   42000  Banglore

In [ ]:
## 2.basic dataframe understanding:-->
df.head(2)    #it will give top 2 rows

     Name  Age  Salary     City
0  Madhav   26   20000    Delhi
1  Lalita   25   32000  Kolkata

In [ ]:
df.tail(2)  #it will give lowest 2 rows

    Name  Age  Salary      City
4  Priya   24   35000     Bihar
5   Mina   23   42000  Banglore

In [ ]:
#want to know how much rows and columns?
#use the shape
df.shape      #6 rows & 4 colm

(6, 4)

In [ ]:
#show columns we use column:
df.columns

Index(['Name', 'Age', 'Salary', 'City'], dtype='object')

In [ ]:
#How to rename the columns name ?
#change the salry colm name to monthly salary:
df.rename(columns={'Salary':'Monthly salary'})

     Name  Age  Monthly salary      City
0  Madhav   26           20000     Delhi
1  Lalita   25           32000   Kolkata
2    Isha   22           28000    gujrat
3   Rohan   27           18000    Orrisa
4   Priya   24           35000     Bihar
5    Mina   23           42000  Banglore

In [ ]:
df      #rename func changed is not changed in the original dataframe-

     Name  Age  Salary      City
0  Madhav   26   20000     Delhi
1  Lalita   25   32000   Kolkata
2    Isha   22   28000    gujrat
3   Rohan   27   18000    Orrisa
4   Priya   24   35000     Bihar
5    Mina   23   42000  Banglore

In [ ]:
#change the salry colm name to monthly salary in original dataframe --
df.rename(columns={'Salary': 'Monthly_salary'},inplace=True)
print(df)

     Name  Age  Monthly_salary      City
0  Madhav   26           20000     Delhi
1  Lalita   25           32000   Kolkata
2    Isha   22           28000    gujrat
3   Rohan   27           18000    Orrisa
4   Priya   24           35000     Bihar
5    Mina   23           42000  Banglore

In [ ]:
#to know  the datatype of dataframe--
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            6 non-null      object
 1   Age             6 non-null      int64
 2   Monthly_salary  6 non-null      int64
 3   City            6 non-null      object
dtypes: int64(2), object(2)
memory usage: 324.0+ bytes

In [ ]:
#to show the statical info--
df.describe()

NameError: name 'df' is not defined

In [ ]:
#3.save data and load data from CSV file--->
df.to_csv('Test Data.csv')        #the file is saved

In [ ]:
#to read or load dataframe csv file--
Load_df=pd.read_csv('Test Data.csv')
print(Load_df)

   Unnamed: 0    Name  Age  Salary      City
0           0  Madhav   26   20000     Delhi
1           1  Lalita   25   32000   Kolkata
2           2    Isha   22   28000    gujrat
3           3   Rohan   27   18000    Orrisa
4           4   Priya   24   35000     Bihar
5           5    Mina   23   42000  Banglore

In [ ]:
# 4.rows and column selection-->
# if i want select only 1 colum
#df[['Name of colm]]
df[['Name','Age']]      #if want multiple column just add the nmae of colm in''

     Name  Age
0  Madhav   26
1  Lalita   25
2    Isha   22
3   Rohan   27
4   Priya   24
5    Mina   23

In [ ]:
#select Rows--
#selecting a row  index named based --
df.loc[df.Name=='Madhav']
#loc=label/name based function

     Name  Age  Monthly_salary   City
0  Madhav   26           20000  Delhi

In [ ]:
#selecting a row  index named based --
df.loc[(df.Name=='Madhav')& (df.Age>=20)]
#put condition also to find the rows

     Name  Age  Monthly_salary   City
0  Madhav   26           20000  Delhi

In [ ]:
df.loc[0:2]     #it add the 0 index to 2 inex

     Name  Age  Monthly_salary     City
0  Madhav   26           20000    Delhi
1  Lalita   25           32000  Kolkata
2    Isha   22           28000   gujrat

In [ ]:
#iloc=index-value based finding of row--
df.iloc[0:2]        #it not add inex 2 last index not included
df.iloc[0]          #we use the start-stop-step

Name              Madhav
Age                   26
Monthly_salary     20000
City               Delhi
Name: 0, dtype: object

In [ ]:
df

     Name  Age  Monthly_salary      City
0  Madhav   26           20000     Delhi
1  Lalita   25           32000   Kolkata
2    Isha   22           28000    gujrat
3   Rohan   27           18000    Orrisa
4   Priya   24           35000     Bihar
5    Mina   23           42000  Banglore

In [ ]:
# 5.filter dataframe-->
df['Age']>25  #filter by age
#want a only true data of condition
df[df['Age']>25]

     Name  Age  Monthly_salary    City
0  Madhav   26           20000   Delhi
3   Rohan   27           18000  Orrisa

In [ ]:
#If we want more filter use & operator and run-->
df[(df['Age']>25)&(df['Monthly_salary']>10000)]

     Name  Age  Monthly_salary    City
0  Madhav   26           20000   Delhi
3   Rohan   27           18000  Orrisa

In [ ]:
#if i want the full dataframe We use Where func with filter-->

#it will give full df with NaN by default--
df.where(df['Age'] >25)

df.where(df['Age'] >25, other='Not eligible')
#it will change the null to=Not eligible

           Name           Age Monthly_salary          City
0        Madhav            26          20000         Delhi
1  Not eligible  Not eligible   Not eligible  Not eligible
2  Not eligible  Not eligible   Not eligible  Not eligible
3         Rohan            27          18000        Orrisa
4  Not eligible  Not eligible   Not eligible  Not eligible
5  Not eligible  Not eligible   Not eligible  Not eligible

In [ ]:
# 6.rows and column operations-->
#add a new column--
df['Team']=['CEO','HR','CTO','DA','MD','OA']
#a new column Team will add with the table or df...
df

     Name  Age  Salary      City Team
0  Madhav   26   20000     Delhi  CEO
1  Lalita   25   32000   Kolkata   HR
2    Isha   22   28000    gujrat  CTO
3   Rohan   27   18000    Orrisa   DA
4   Priya   24   35000     Bihar   MD
5    Mina   23   42000  Banglore   OA

In [ ]:
#if we want to add column with multiply the value like bonus-->
df['Bonus']=df['Monthly_salary']*0.20
df

      Name Age  Monthly_salary      City Team    Bonus
0   Madhav  26           58000     Delhi  CEO  11600.0
1   Lalita  25           32000   Kolkata   HR   6400.0
2     Isha  22           28000    gujrat  CTO   5600.0
3    Rohan  27           18000    Orrisa   DA   3600.0
4    Priya  24           35000     Bihar   MD   7000.0
5     Mina  23           42000  Banglore   OA   8400.0
6      Ram  30           35000      Pune   SD   7000.0
7      Ram  30           35000      Pune   SD   7000.0
8      Ram  30           35000      Pune   SD   7000.0
9   Keshav  33           22000     Assam   TC   4400.0
10     Ram  30           35000      Pune   SD   7000.0
11  Keshav  33           22000     Assam   TC   4400.0
12     Ram  30           35000      Pune   SD   7000.0
13  Keshav  33           22000     Assam   TC   4400.0
14     Ram  30           35000      Pune   SD   7000.0
15  Keshav  33           22000     Assam   TC   4400.0
16     Ram  30           35000      Pune   SD   7000.0
17     Ram  30           35000      Pune   SD   7000.0
18     Ram  30           35000      Pune   SD   7000.0

In [ ]:
#add a new rows-->
#we use a loc method and type data according to the no of column:
df.loc[len(df)] = ['Ram','30',35000,'Pune','SD',2000]
df

In [ ]:
len(df)       #12 no of rows

6

In [ ]:
#update the value-->
#put the loc func and by using index name no you update--
df.loc[0,'Monthly_salary'] = 58000
df

     Name  Age  Salary      City Team  Monthly_salary
0  Madhav   26   20000     Delhi  CEO         58000.0
1  Lalita   25   32000   Kolkata   HR             NaN
2    Isha   22   28000    gujrat  CTO             NaN
3   Rohan   27   18000    Orrisa   DA             NaN
4   Priya   24   35000     Bihar   MD             NaN
5    Mina   23   42000  Banglore   OA             NaN

In [ ]:
df.loc[2,'Team']='MD'

In [ ]:
#update value using column name--
df.loc[df.Name=='Madhav','Monthly_salary']=58000

In [ ]:
df.drop(df[df.Name=='Ram'].index)

     Name  Age  Salary      City Team  Monthly_salary
0  Madhav   26   20000     Delhi  CEO         58000.0
1  Lalita   25   32000   Kolkata   HR             NaN
2    Isha   22   28000    gujrat   MD             NaN
3   Rohan   27   18000    Orrisa   DA             NaN
4   Priya   24   35000     Bihar   MD             NaN
5    Mina   23   42000  Banglore   OA             NaN

In [ ]:
df.drop(['Bonus','Team'], axis=1) #delete multiple columns

      Name Age  Monthly_salary      City
0   Madhav  26           58000     Delhi
1   Lalita  25           32000   Kolkata
2     Isha  22           28000    gujrat
3    Rohan  27           18000    Orrisa
4    Priya  24           35000     Bihar
5     Mina  23           42000  Banglore
6      Ram  30           35000      Pune
7      Ram  30           35000      Pune
8      Ram  30           35000      Pune
9   Keshav  33           22000     Assam
10     Ram  30           35000      Pune
11  Keshav  33           22000     Assam
12     Ram  30           35000      Pune
13  Keshav  33           22000     Assam
14     Ram  30           35000      Pune
15  Keshav  33           22000     Assam
16     Ram  30           35000      Pune
17     Ram  30           35000      Pune
18     Ram  30           35000      Pune
19     Ram  30           35000      Pune
20     Ram  30           35000      Pune
21     Ram  30           35000      Pune

In [ ]:
df1=df.drop(df[df.Name=='Ram'].index)
df1

NameError: name 'df' is not defined

In [ ]:
#delete rows bases on index--
df.drop(13,axis=0)

      Name Age  Monthly_salary      City Team
0   Madhav  26           58000     Delhi  CEO
1   Lalita  25           32000   Kolkata   HR
2     Isha  22           28000    gujrat   MD
3    Rohan  27           18000    Orrisa   DA
4    Priya  24           35000     Bihar   MD
5     Mina  23           42000  Banglore   OA
6      Ram  30           35000      Pune   SD
7      Ram  30           35000      Pune   SD
8      Ram  30           35000      Pune   SD
9   Keshav  33           22000     Assam   TC
10     Ram  30           35000      Pune   SD
11  Keshav  33           22000     Assam   TC
12     Ram  30           35000      Pune   SD
14     Ram  30           35000      Pune   SD
15  Keshav  33           22000     Assam   TC
16     Ram  30           35000      Pune   SD
17     Ram  30           35000      Pune   SD
18     Ram  30           35000      Pune   SD
19     Ram  30           35000      Pune   SD
20     Ram  30           35000      Pune   SD
21     Ram  30           35000      Pune   SD

In [ ]:
#For sorting a value--
df.sort_values('Monthly_salary')    #ascending order by default

      Name Age  Monthly_salary      City Team
3    Rohan  27           18000    Orrisa   DA
15  Keshav  33           22000     Assam   TC
11  Keshav  33           22000     Assam   TC
9   Keshav  33           22000     Assam   TC
13  Keshav  33           22000     Assam   TC
2     Isha  22           28000    gujrat   MD
1   Lalita  25           32000   Kolkata   HR
4    Priya  24           35000     Bihar   MD
10     Ram  30           35000      Pune   SD
8      Ram  30           35000      Pune   SD
6      Ram  30           35000      Pune   SD
7      Ram  30           35000      Pune   SD
12     Ram  30           35000      Pune   SD
14     Ram  30           35000      Pune   SD
17     Ram  30           35000      Pune   SD
16     Ram  30           35000      Pune   SD
20     Ram  30           35000      Pune   SD
21     Ram  30           35000      Pune   SD
18     Ram  30           35000      Pune   SD
19     Ram  30           35000      Pune   SD
5     Mina  23           42000  Banglore   OA
0   Madhav  26           58000     Delhi  CEO

In [ ]:
df.sort_values('Monthly_salary', ascending=False)   #decending order put False

      Name Age  Monthly_salary      City Team
0   Madhav  26           58000     Delhi  CEO
5     Mina  23           42000  Banglore   OA
4    Priya  24           35000     Bihar   MD
8      Ram  30           35000      Pune   SD
7      Ram  30           35000      Pune   SD
6      Ram  30           35000      Pune   SD
20     Ram  30           35000      Pune   SD
19     Ram  30           35000      Pune   SD
21     Ram  30           35000      Pune   SD
10     Ram  30           35000      Pune   SD
12     Ram  30           35000      Pune   SD
17     Ram  30           35000      Pune   SD
16     Ram  30           35000      Pune   SD
14     Ram  30           35000      Pune   SD
18     Ram  30           35000      Pune   SD
1   Lalita  25           32000   Kolkata   HR
2     Isha  22           28000    gujrat   MD
13  Keshav  33           22000     Assam   TC
9   Keshav  33           22000     Assam   TC
11  Keshav  33           22000     Assam   TC
15  Keshav  33           22000     Assam   TC
3    Rohan  27           18000    Orrisa   DA

In [ ]:
import pandas as pd

Data1={
    'Name':['Mohan','Devika','Isha','Yash'],
    'Age':[22,28,31,19],
    'City':['Delhi','Pune','Agra','UP'],
    'Salary':[20000,15000,35000,18000]
}
df=pd.DataFrame(Data1)
print(df)

     Name  Age   City  Salary
0   Mohan   22  Delhi   20000
1  Devika   28   Pune   15000
2    Isha   31   Agra   35000
3    Yash   19     UP   18000

In [ ]:
df.shape    #4row and 3 column

(4, 3)

In [ ]:
df['DOJ'] = ['2024-01-01','2024-03-28','2024-03-03','2024-02-15']
df

     Name  Age   City         DOJ
0   Mohan   22  Delhi  2024-01-01
1  Devika   28   Pune  2024-03-28
2    Isha   31   Agra  2024-03-03
3    Yash   19     UP  2024-02-15

In [ ]:
df.loc[df.Name=='Yash','City' ]='Goa'
df

     Name  Age   City         DOJ
0   Mohan   22  Delhi  2024-01-01
1  Devika   28   Pune  2024-03-28
2    Isha   31   Agra  2024-03-03
3    Yash   19    Goa  2024-02-15

In [ ]:
#9.aggregation and Groupby-->
#want to know the count of Team :
df['Name'].value_counts()

NameError: name 'df' is not defined

In [ ]:
#groupby--
df.groupby('City')['Salary'].sum()

City
Agra     35000
Delhi    20000
Pune     15000
UP       18000
Name: Salary, dtype: int64

In [ ]:
#groupby+agg
#if we want the count of name and mean & avg of salry we write-->
df.groupby('City').agg({'Salary':'mean','Name':'count'})

        Salary  Name
City
Agra   35000.0     1
Delhi  20000.0     1
Pune   15000.0     1
UP     18000.0     1

In [ ]:
# 10.concatenate and merge the dataframe-->(JOINS)
data_A=pd.DataFrame({'ID':[1,2,3],'Name':['A','B','C']})
print(data_A)

   ID Name
0   1    A
1   2    B
2   3    C

In [ ]:
data_B=pd.DataFrame({'ID':[1,2,3,4],'Score':[88,96,77,79]})
print(data_B)

   ID  Score
0   1     88
1   2     96
2   3     77
3   4     79

In [ ]:
pd.concat([data_A,data_B],axis=0) #row wise concat

   ID Name  Score
0   1    A    NaN
1   2    B    NaN
2   3    C    NaN
0   1  NaN   88.0
1   2  NaN   96.0
2   3  NaN   77.0
3   4  NaN   79.0

In [ ]:
pd.concat([data_A,data_B],axis=1)   #column wise concat

    ID Name  ID  Score
0  1.0    A   1     88
1  2.0    B   2     96
2  3.0    C   3     77
3  NaN  NaN   4     79

In [ ]:
#merge=join
pd.merge(data_A,data_B,how='inner' ,on='ID') #put coomon cloumn ID
#by default inner

   ID Name  Score
0   1    A     88
1   2    B     96
2   3    C     77

In [ ]:
pd.merge(data_A,data_B,how='inner' ,left_on='ID'right_on='ID',)
#for multiple common column